# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Build and Test on Push"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/backend/EzeGeo.sln
    - name: Build
      run: dotnet build src/backend/EzeGeo.sln --no-restore
    - name: Test
      run: dotnet test src/backend/EzeGeo.sln --no-build --verbosity normal
